runtime: php81 # Replace with php74 to use PHP 7.4

# [START configuration]
# What sets the type of server we get. FX servers are "free" for up to 28 hours
# a day but have low resources.
# Default should be the FX class but we'll mark it here.
# instance_class: F1
# [END configuration]

# [START configuration]
handlers:
  # Serve a directory as a static resource.
  - url: /src/templates/css
    static_dir: src/templates/css

  - url: /src/templates/js
    static_dir: src/templates/js

# Serve images as static resources.
# - url: /(.+\.(gif|png|jpg))$
#   static_files: \1
#   upload: .+\.(gif|png|jpg)$

# Serve your app through a front controller at index.php or public/index.php.
  - url: .*
    script: auto
# [END configuration]

# [START configuration]
runtime_config:
  enable_stackdriver_integration: true,
  document_root: .
# [END configuration]

# [START configuration]
readiness_check:
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 600
# [END configuration]

# [START configuration]
beta_settings:
  cloud_sql_instances: burnished-flare-348022:us-west1:demo-db-alpha # This will be unique to the cloud project!
# [END configuration]