runtime: php81 # Replace with php74 to use PHP 7.4

# [START configuration]
# What sets the type of server we get. FX servers are "free" for up to 28 hours
# a day but have low resources.
# Default should be the FX class but we'll mark it here.
# instance_class: F1
# [END configuration]

# [START configuration]
handlers:
  # Setup the static resource directories.
  - url: /src/templates/css
    static_dir: src/templates/css

  - url: /src/templates/js
    static_dir: src/templates/js

  - url: /src/images/fav
    static_dir: src/images/fav

  # Handle any favicon requests
  # NOTE: It's wild b/c google debugger is weird. Probably pointless but kinda fun.
  - url: /(.*)\.?favicon.ico$
    static_files: src/images/fav/favicon.ico
    upload: (.*)\.?favicon.ico$

  # Serve images as static resources.
  - url: /(.+\.(gif|png|jpg))$
    static_files: \1
    upload: .+\.(gif|png|jpg)$

# Serve the app through a front controller at index.php or public/index.php.
  - url: .*
    script: auto
# [END configuration]

# [START configuration]
runtime_config:
  enable_stackdriver_integration: true,
  document_root: .
# [END configuration]

# [START configuration]
readiness_check:
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 600
# [END configuration]
