<?php
use Utils\HtmlUtils;
// There's no particular reason you can't just plop a widget here
// This does require widgets logic to be more rigid but also pretty handy imo
use HtmlFramework\Widget\BlockOFun;
?>


<?php
/**
 * Using PHP to generate HTML in templates is good practice. Just don't be modifying
 * data in a Packet.
 */
$h1Text = 'This is where we can add ' . HtmlUtils::makeFunSpan('specific page elements');
?>
<?= HtmlUtils::makeH1Element($h1Text, 'fun') ?>
<p>The parsable text is <?= HtmlUtils::makeFunSpan('cool') ?> but has <?= HtmlUtils::makeFunSpan('limitations') ?></p>
<p>This is the template where we can just <?= HtmlUtils::makeFunSpanFromArray(['do', 'random', 'things']) ?></p>

<?= (new BlockOFun())->getHtml(); ?>