<?php
/**
 * Using PHP to generate HTML in templates is good practice. Just don't be modifying
 * data in a Packet.
 */
use Utils\HtmlUtils;

// <div id="raw-text-main-article-container" class="hidden">
//  <div><code>{$rawText}</code></div>
//  <div><a>{$toggleBackHtml}</a></div>
// </div>
$rawMainArticleTxtDiv = HtmlUtils::makeDivElement("<code>{$this->getData('escapedMainArticleTxt')}</code>");
$toggleHtmlTxt = '[Click Here To View Parsed Text]';
$toggleHtmlBtn = "<a href=\"#toggleParser\">{$toggleHtmlTxt}</a>";
$toggleContainer = HtmlUtils::makeDivElement($toggleHtmlBtn, ['id' => 'view-parse-toggle-btn']);
$rawMainArticleTxtContainer = HtmlUtils::makeDivElement($rawMainArticleTxtDiv . $toggleContainer,['id' => 'raw-text-main-article-container', 'class' => 'hidden']);

$fP1 = HtmlUtils::makePElement("Each page has unique elements, however, there is common code across them all.");

?>

<!-- This is the Welcome Page "template" & you can write any random HTML or PHP logic you want -->
<?= $rawMainArticleTxtContainer ?>
<?= $fP1 ?>

<div class="robot-fun-container">
   <div class="robot-fun-img-container fun-btn">
      <img src="/src/images/site/fun-robot.png" />
   </div>
   <div class="robot-fun-txt-container" >
      <h3 class="fun">Try clicking the robot.</h3>
      <p>Can you figure out how to do <span class="fun">this</span> on <span class="fun">any page</span><span class="fun">?</span></p>
   </div>
</div>