<div id="robots-header-container">
   <div class="robots-header-content-background">
      <moon class="robots-header-moon">&nbsp;</moon>
      <img src="/src/images/site/robots/c2d2.png" class="robots-header-robot robots-header-left-side js-header-robot" />
      <img src="/src/images/site/robots/c2d2.png" class="robots-header-robot robots-header-right-side js-header-robot" />
   </div>
   <div class="robots-header-text-container">
      <h1>Robots</h1>
      <p>Frankie, C2D2 & <span style"whitespace:no-wrap">Tractor Hacking<span></p>
   </div>
</div>