<div id="welcome-header-container">
   <div class="welcome-header-floating-circle-container">
      <img class="js-floating-circle floating-circle slider-container-transition" src="src/images/site/welcome/orange_circle.png" />
      <img class="js-floating-circle floating-circle top-floating-circle slider-container-transition" src="src/images/site/welcome/white_strips_circle.png" />
   </div>
   <div id="welcome-header-slash-container" class="welcome-header-slash-container js-welcome-header-slash-container">
      <img id="welcome-header-slash" class="js-moving-slash js-animate-slash welcome-header-slash" src="src/images/site/welcome/orange_lines.png" />
   </div>
   <div id="welcome-header-x-container" class="js-welcome-header-x-container welcome-header-x-container">
      <img class="js-floating-x welcome-header-x" src="src/images/site/welcome/x.png" />
      <img class="js-floating-x welcome-header-x" src="src/images/site/welcome/x.png" />
      <img class="js-floating-x welcome-header-x" src="src/images/site/welcome/x.png" />
      <img class="js-floating-x welcome-header-x" src="src/images/site/welcome/x.png" />
   </div>
</div>
