<div id="welcome-header-container">
   <div class="welcome-header-floating-circle-container">
      <img class="js-floating-circle floating-circle slider-container-transition" src="src/images/site/welcome/orange_circle.png" />
      <img class="js-floating-circle floating-circle top-floating-circle slider-container-transition" src="src/images/site/welcome/white_strips_circle.png" />
   </div>
   <h1>Hello World</h1>
</div>
