<div id="welcome-header-container">
   <div class="welcome-header-floating-circle-container">
      <img class="js-floating-circle floating-circle slider-container-transition" src="src/images/site/welcome/orange_circle.png" />
      <img class="js-floating-circle floating-circle top-floating-circle slider-container-transition" src="src/images/site/welcome/white_strips_circle.png" />
   </div>
   <div class="js-welcome-header-x-container welcome-header-x-container">
      <img class="js-floating-x welcome-header-x" src="src/images/site/welcome/x.png" />
      <img class="js-floating-x welcome-header-x" src="src/images/site/welcome/x.png" />
      <img class="js-floating-x welcome-header-x" src="src/images/site/welcome/x.png" />
      <img class="js-floating-x welcome-header-x" src="src/images/site/welcome/x.png" />
   </div>
   <div class="welcome-header-floating-circle-container right-side">
      <img class="js-floating-circle floating-circle slider-container-transition" src="src/images/site/welcome/orange_circle.png" />
      <img class="js-floating-circle floating-circle top-floating-circle slider-container-transition" src="src/images/site/welcome/white_strips_circle.png" />
   </div>
   <div class="js-welcome-header-x-container welcome-header-x-container right-side">
      <img class="js-floating-x welcome-header-x" src="src/images/site/welcome/x.png" />
      <img class="js-floating-x welcome-header-x" src="src/images/site/welcome/x.png" />
      <img class="js-floating-x welcome-header-x" src="src/images/site/welcome/x.png" />
      <img class="js-floating-x welcome-header-x" src="src/images/site/welcome/x.png" />
   </div>
   <div id="welcome-header-slash-container" class="welcome-header-slash-container js-welcome-header-slash-container">
      <img id="welcome-header-slash" class="js-moving-slash js-animate-slash welcome-header-slash" src="src/images/site/welcome/orange_lines.png" />
   </div>
   <div class="welcome-header-contact-info-container">
      <div class="welcome-header-contact-info-image-container">
         <img class="welcome-header-contact-info-image" src="src/images/site/welcome/chris_circle.png" />
      </div>
      <div class="welcome-header-contact-info-text-container">
         <div class="welcome-header-contact-info-welcome-container">
            <h2 class="js-hidden-text-container js-delay-one hidden-text-container">
               <span class="hidden-text-concealer">&nbsp;</span>
               <span class="hidden-text">Hi, I'm Chris</span>
            </h2>
         </div>
         <div class="welcome-header-contact-info-position-container">
            <p class="js-hidden-text-container js-delay-two hidden-text-container">
               <span class="hidden-text-concealer">&nbsp;</span>
               <span class="hidden-text">Senior Software Engineer</span>
            </p>
         </div>
         <div class="welcome-header-contact-info-details-container">
            <div class="welcome-header-contact-info-data">
               <div class="welcome-header-contact-icon">&#x260F;</div>
               <p class="js-hidden-text-container js-delay-three hidden-text-container">
                  <span class="hidden-text-concealer">&nbsp;</span>
                   <span class="hidden-text">+123-456-7890</span>
               </p>
            </div>
            <div class="welcome-header-contact-info-data">
               <div class="welcome-header-contact-icon">&#x261E;</div>
               <p class="js-hidden-text-container js-delay-four hidden-text-container">
                  <span class="hidden-text-concealer">&nbsp;</span>
                  <span class="hidden-text"><a href="https://www.github.com/cdcline">www.github.com/cdcline</a></span>
               </p>
            </div>
            <div class="welcome-header-contact-info-data">
               <div class="welcome-header-contact-icon">&#9993;</div>
               <p class="js-hidden-text-container js-delay-five hidden-text-container">
                  <span class="hidden-text-concealer">&nbsp;</span>
                  <span class="hidden-text"><a href="mailto:cdcline+demo-site@gmail.com">cdcline@gmail.com</a></span>
               </p>
            </div>
            <div class="welcome-header-contact-info-data">
               <div class="welcome-header-contact-icon">&#x2624;</div>
               <p class="js-hidden-text-container js-delay-six hidden-text-container">
                  <span class="hidden-text-concealer">&nbsp;</span>
                  <span class="hidden-text">123 Anywhere St, Any City</span>
               </p>
            </div>
         </div>
      </div>
   </div>
</div>
