<div class="svg-container">
   <svg class="svg-defs">
      <defs>
         <clipPath id="myCurve" clipPathUnits="objectBoundingBox">
            <path d="M .36,0
                     C .40,.40, .60,.50, .71,.20
                     C .80,.00, .90,.12, .80,.25
                     S .8,1, .56,.80
                     S .2,.50, .3,1
                     L 0,1
                     L 0,0
                     Z" />
         </clipPath>
      </defs>
   </svg>
</div>

<div id="work-header-container">
   <div id="work-header-background-container" class="work-header-content-background">
      <shape class="shape shader"></shape>
      <shape id="header-curve" class="shape curve"></shape>
   </div>
   <div class="work-header-text-container">
      <h1>Resume</h1>
   </div>
</div>
