<body>
   <div class="page-background-container">
      <div id="background-container" class="background-container"></div>
      <div class="page-container">
         <div class="body-content-container">
            <?= $this->printHeader() ?>
            <?= $this->printSection() ?>

            <?= $this->printPageFooter() ?>
         </div>
         <div class="copyright-container">
            <div>©2022 C.D.CLINE</div>
         </div>
         <?= $this->printMobileFooter() ?>
      </div>
   </div>
</body>
