<footer>
   <div class="links-container">
      <?php foreach ($this->getPacketData('footerRows') as $navRow) : ?>
         <div class="link-container">
            <a href="<?= $navRow['url'] ?>"><span><?= $navRow['nav_string'] ?></span></a>
            <span class="display-text-bold-hack-container"><?= $navRow['nav_string'] ?></span>
         </div>
      <?php endforeach ?>
   </div>
</footer>
