<?php
use Utils\HtmlUtils;

$numColors = 4;
$buildContainer = function($url, $i) use ($numColors) {
   $colorIndex = ($i % $numColors) + 1;
   return "<a class=\"circle-container\" href=\"{$url}\"><div class=\"circle color-{$colorIndex}\">&nbsp;</div></a>";
};

$linksHTML = '';
$count = 0;
foreach ($this->packet->getFooterRows() as $navRow) {
   $linksHTML .= $buildContainer($navRow['url'], $count++);
}

$linksContainerHTML = "<div class=\"links-container\">{$linksHTML}</div>";
?>

<footer class="fixed-footer">
   <?= $linksContainerHTML ?>
</footer>

<footer>
   <?= $linksContainerHTML ?>
</footer>