<?php
use Utils\HtmlUtils;

$buildContainer = function($url, $navString) {
   $linkSpan = HtmlUtils::makeSpanElement($navString, []);
   $boldSpanHack = HtmlUtils::makeSpanElement($navString, ['class' => 'display-text-bold-hack-container']);
   $link = "<a href=\"{$url}\">{$linkSpan}</a>";
   return HtmlUtils::makeDivElement($link . $boldSpanHack, ['class' => 'link-container']);
};

$linksHTML = '';
foreach ($this->packet->getFooterRows() as $navRow) {
   $linksHTML .= $buildContainer($navRow['url'], $navRow['nav_string']);
}

$linksContainerHTML = "<div class=\"links-container\">{$linksHTML}</div>";
?>

<footer class="fixed-footer">
   <?= $linksContainerHTML ?>
</footer>

<footer>
   <?= $linksContainerHTML ?>
</footer>